python3 ID3.py car/train.csv car/test.csv H 1
python3 ID3.py car/train.csv car/test.csv H 2
python3 ID3.py car/train.csv car/test.csv H 3
python3 ID3.py car/train.csv car/test.csv H 4
python3 ID3.py car/train.csv car/test.csv H 5
python3 ID3.py car/train.csv car/test.csv H 6
python3 ID3.py car/train.csv car/test.csv ME 1
python3 ID3.py car/train.csv car/test.csv ME 2
python3 ID3.py car/train.csv car/test.csv ME 3
python3 ID3.py car/train.csv car/test.csv ME 4
python3 ID3.py car/train.csv car/test.csv ME 5
python3 ID3.py car/train.csv car/test.csv ME 6
python3 ID3.py car/train.csv car/test.csv GI 1
python3 ID3.py car/train.csv car/test.csv GI 2
python3 ID3.py car/train.csv car/test.csv GI 3
python3 ID3.py car/train.csv car/test.csv GI 4
python3 ID3.py car/train.csv car/test.csv GI 5
python3 ID3.py car/train.csv car/test.csv GI 6